### ISSUE TITLE
ch3 code

### ISSUE THREAD

**Issue by mpena2099** [dristic/webrtc-book#1]
Hi! 

I don't think ch3 code is working anymore, on new versions of Chrome... :(

Thanks!
Mauricio

**Comment by dristic** [comment]
Hey thanks for the report! What error are you seeing?

I have not taken a look at this in a while so chances are many things are out of date.

**Comment by mpena2099** [comment]
Hi @dristic !

Exactly the same error as  here: https://stackoverflow.com/questions/39363149/webrtc-referenceerror-webkitrtcpeerconnection-is-not-defined

**Comment by dristic** [comment]
Okay it looks like https://github.com/dristic/webrtc-book/commit/d46c0c14c31cf0a5b3b76f85286f3c5b23e2de16 is the change the question suggests

I will have to update all the chapters to reflect this as well.

Does that fix the issue for you?

**Comment by mpena2099** [comment]
I don't think so. There is a warning: "[Deprecation] URL.createObjectURL with media streams is deprecated and will be removed in M68, around July 2018. Please use HTMLMediaElement.srcObject instead. See https://www.chromestatus.com/features/5618491470118912 for more details."

And I'm not seening two images, just one.

![tela1](https://user-images.githubusercontent.com/1200886/43238547-f8bd8b48-9064-11e8-9096-b4d2bbd21f43.png)

**Comment by morxw** [comment]
Hey there Dan.
I also bought your book and noticed some Problems at ch3. I'm really not a .js pro so it's quite difficult to find working replacements for all the deprecated methods and calls. I understand that when you wrote the book the API was still quite experimental and not many standards existed back then (As you wrote at the beginning) but now there are, so i hoped maybe you could update the repo here so i can continue with your book. :) 

I have the same problem mpena2099 had. I replaced the lines 
`xyzVideo.src = window.URL.createObjectURL(stream);`
with 
`xyzVideo.srcObject = stream;`
So i got the direct webcam output running but the "incoming" Video seems not to work.
Seems that the addStream and onaddstream statements are deprecated as well in:
`yourConnection.addStream(stream);
  theirConnection.onaddstream = function (e) {
    console.log("This Text will never get shown, since function never gets called");
    theirVideo.srcObject = e.stream;
  };`

Would be so glad about an updated example Repository that works in current browsers. Thanks in advance. :-)
- Moritz

**Comment by dristic** [comment]
Hey sorry I have not kept this up to date.

Can I suggest checking out the examples here: https://webrtc.github.io/samples/src/content/peerconnection/pc1/

They look to be up to date and have the add video track code you need, specifically
https://github.com/webrtc/samples/blob/gh-pages/src/content/peerconnection/pc1/js/main.js#L79

The book is still a great resource for understanding the general process of WebRTC and the major concepts involved. For working examples I recommend the webrtc samples repository as this has more contributors and will be kept up to date when the specification changes.
